language: elm

script: elm-format --validate . && elm-test && make dist

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: target
  github_token: $GITHUB_TOKEN
  fqdn: pitch.bzzt.net
  on:
    branch: master
