language: elm

script: elm-format --validate . && elm-test && mkdir target && elm make src/Main.elm --output=target/main.js && cp index.html target && cp -r assets target && cp -r js target

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: target
  github_token: $GITHUB_TOKEN
  on:
    branch: master
